// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalTliwhgMFflrCvHoiw8uReX4bEOgj9U',
    appId: '1:236417618816:web:3be0f302134488603d6765',
    messagingSenderId: '236417618816',
    projectId: 'appathon-9530d',
    authDomain: 'appathon-9530d.firebaseapp.com',
    storageBucket: 'appathon-9530d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHromEuLe8BwRqBtiw6N4pY6DWle_ZWbA',
    appId: '1:236417618816:android:69017f8d44c6a2aa3d6765',
    messagingSenderId: '236417618816',
    projectId: 'appathon-9530d',
    storageBucket: 'appathon-9530d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1p5vl-jXn734buIWbG3RCjt9-UQZxAww',
    appId: '1:236417618816:ios:66492b566202d8fc3d6765',
    messagingSenderId: '236417618816',
    projectId: 'appathon-9530d',
    storageBucket: 'appathon-9530d.appspot.com',
    iosBundleId: 'com.example.appathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1p5vl-jXn734buIWbG3RCjt9-UQZxAww',
    appId: '1:236417618816:ios:66492b566202d8fc3d6765',
    messagingSenderId: '236417618816',
    projectId: 'appathon-9530d',
    storageBucket: 'appathon-9530d.appspot.com',
    iosBundleId: 'com.example.appathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalTliwhgMFflrCvHoiw8uReX4bEOgj9U',
    appId: '1:236417618816:web:91ef3442930f39653d6765',
    messagingSenderId: '236417618816',
    projectId: 'appathon-9530d',
    authDomain: 'appathon-9530d.firebaseapp.com',
    storageBucket: 'appathon-9530d.appspot.com',
  );
}
